### ISSUE TITLE
import most vendored files into this repo

### ISSUE THREAD

**Issue by clux** [kube-rs/website#11]
Having canonical versions outside the website repo is awkward for editing of this website. Vendoring is unexpected and complicates contributions, and many files do not need to be at the org level.

### stuff easy to move

- [x] `ADOPTERS` (from kube-rs repo) - #15 + kube-rs/kube-rs#867
- [x] `MAINTAINERS` (from .github repo) https://github.com/kube-rs/.github/commit/0805d875a5c4b2f2fd239845b2b3c41ba1969035 + #16 + kube-rs/kube-rs#868 + sync commit
- [x] `GOVERNANCE` (from .github repo) - #16 + https://github.com/kube-rs/.github/commit/ccb3948d5d9e79a0382888c452e5de3416112064 + kube-rs/kube-rs#868 + sync commit
- [x] `TOOLS` (from .github repo) https://github.com/kube-rs/kube-rs/commit/057b935fbf0c11662bcc5f16efed4e85fe98a5ea + https://github.com/kube-rs/website/commit/fda9f2255bbfa90ba9f3502b0d350638e7c6f5cf + https://github.com/kube-rs/.github/commit/7d1118c02ab9b38f17c9d1defde555dab324092a
- [x] `ARCHITECTURE` (from kube-rs repo) #16 + kube-rs/kube-rs#868 + sync commit

### stuff hard to move

- `CONTRIBUTING` (from kube-rs and mirrored in .github repo) - shows up on PR creation as suggestion
- `SECURITY` (from kube-rs and mirrored in .github repo) - shows up as security policy when creating issues

these files **could** be replaced with a stub that links to the one in this repo if we move it, but it would make the contribution experience on github worse (more clicks to figure out what is what)

it's probably better to ignore importing these, and ensure they either don't link to sibling docs (so it's embedded better on the website), or link to them in a way we can fixup after importing.

### probably impossible to move

- `CHANGELOG` (from kube-rs) - needs to be generated in that repo
- `getting-started` (hacked from README in kube-rs) - might be better to rewrite?

the changelog is fine. it's meant to be an import dump, but maybe it's worth rethinking the readme anyway.

### care

doing this would break some links from markdown docs in other repos, and also break best practice docs links in the [best practice badge](https://bestpractices.coreinfrastructure.org/en/projects/5413), but should be easy to fix.

possibly some cncf-wide links need to be changed upstream, need to revisit the upstream donation issue to verify these files are not linked to directly. think possibly governance is linked somewhere.

### benefits

- allows enabling [edit button](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button) for ez website contribution
- limit pr mistakes from people editing website and not seeing the warning header
- allows unmovable docs to link to the website for users to get a better overview

i think we should import the easy stuff, and then improve the rest iteratively as we go.
